#use_frameworks!

platform :ios, '9.0'

target 'TMUIKit_Example' do
  pod 'TMUIKit', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'ReactiveObjC'
  
  
  target 'TMUIKit_Tests' do
    inherit! :search_paths

    
  end
end
