source 'https://github.com/CocoaPods/Specs.git'   #官方仓库地址
source 'git@repo.we.com:ios/tspecsrepo.git'       #私有仓库地址
#use_frameworks!

platform :ios, '9.0'

target 'TMUIKit_Example' do
  pod 'TMUIKit', :path => '../TMUIKit_Debug.podspec'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'ReactiveObjC'
  pod 'MJRefresh'
  pod 'YYWebImage'
  
  
  target 'TMUIKit_Tests' do
    inherit! :search_paths

    
  end
end
