source 'https://github.com/CocoaPods/Specs.git'   #官方仓库地址
source 'git@repo.we.com:ios/tspecsrepo.git'       #私有仓库地址

#命令写在这里也是等效， 已移动到Podfile_local中，避免git提交冲突等场景
#plugin 'cocoapods-imy-bin'
#use_binaries!
platform :ios, '9.0'
target 'TMToast-Demo' do
	pod 'TMToast', :path => 'TMToast.podspec'
end
  
